# Generated by Django 3.1.2 on 2020-10-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='short_desc',
        ),
    ]
