# Generated by Django 3.0.8 on 2020-10-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201012_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodval',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
