# Generated by Django 3.1.2 on 2020-10-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_article_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='(максимальное число символов: неограниченно)', verbose_name='Контент статьи ')),
                ('img', models.ImageField(blank=True, default='static/Shop/images/default.png', help_text='(желательно 250Х250px)', upload_to='media/photos', verbose_name='Загрузка картинки')),
            ],
        ),
    ]
