# Generated by Django 3.0.8 on 2020-10-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201012_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchar',
            name='price',
            field=models.IntegerField(help_text='Enter price'),
        ),
    ]
