# Generated by Django 3.1.2 on 2020-10-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201025_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='slogan',
            field=models.CharField(default='Очень, крутой, магазин, корейской, продукции', help_text='(ВАЖНО: слова писать через запятую и пробел, пример: слово1, слово2, ... )', max_length=255, verbose_name='Слоган на главной странице '),
        ),
    ]
