# Generated by Django 3.0.8 on 2020-10-17 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201012_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchar',
            name='props',
            field=models.ManyToManyField(through='shop.ProdVal', to='shop.Property'),
        ),
        migrations.AlterField(
            model_name='productchar',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate', models.IntegerField(default=0)),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
