# Generated by Django 3.1.2 on 2020-10-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_siteprofile_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productchar'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='instagram',
            field=models.CharField(blank=True, help_text='(максимальное число символов: 50)', max_length=50, verbose_name='Ссылка на Instagram '),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='whatsup',
            field=models.CharField(blank=True, help_text='(максимальное число символов: 50)', max_length=50, verbose_name="Ссылка на What's Up "),
        ),
    ]
