# Generated by Django 3.1.2 on 2020-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201025_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='product',
            field=models.CharField(default='Не указан', max_length=255, verbose_name='Позиция '),
        ),
    ]
