# Generated by Django 3.1.2 on 2020-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('address', models.CharField(max_length=100, verbose_name='Адресс клиента')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон клиента')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Общая сумма заказа')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('checked', models.CharField(choices=[('Не проверен', 'Не проверен'), ('Проверен', 'Проверен')], default='Не проверен', max_length=20, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
