# Generated by Django 3.0.8 on 2020-10-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
