# Generated by Django 3.0.8 on 2020-10-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productcomment_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
