# Generated by Django 3.1.2 on 2020-11-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201111_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchar',
            name='sold',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
